using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.Runtime;

namespace MyPlugin;

// TODO: Generated by /lisp-to-dotnet migration — replace this stub with migrated commands.
// Design Automation only — no interactive prompts, no dialogs, ever. Inputs come from
// params.json, deserialized into a per-command Models/<CommandName>Input.cs record
// (created in Step 3 once the original LISP's getpoint/getstring/getfiled calls are known).
// See SKILL.md's Design Automation Guardrail for the full rule.
public class Commands
{
    [CommandMethod("MYPLUGIN_CMD")]
    public void RunCommand()
    {
        var db = HostApplicationServices.WorkingDatabase;

        // TODO: once Models/MyPluginCmdInput.cs exists —
        //   string paramsPath = Path.Combine(Environment.CurrentDirectory, "params.json");
        //   var input = JsonSerializer.Deserialize<MyPluginCmdInput>(File.ReadAllText(paramsPath))
        //       ?? throw new InvalidOperationException($"Failed to parse {paramsPath}");

        using var tr = db.TransactionManager.StartTransaction();
        try
        {
            // TODO: migration body goes here — read inputs from the deserialized params
            tr.Commit();
        }
        catch (System.Exception)
        {
            tr.Abort();
            throw; // let the DA WorkItem report the failure — no interactive session to recover into
        }
    }
}
