using Autodesk.AutoCAD.ApplicationServices;
using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.Runtime;

namespace MyPlugin;

// TODO: Generated by /lisp-to-dotnet migration — replace this stub with migrated commands.
public class Commands
{
    [CommandMethod("MYPLUGIN_CMD")]
    public void RunCommand()
    {
        var doc = Application.DocumentManager.MdiActiveDocument;
        var db  = doc.Database;
        var ed  = doc.Editor;

        using var tr = db.TransactionManager.StartTransaction();
        try
        {
            // TODO: migration body goes here
            ed.WriteMessage("\nMYPLUGIN_CMD executed.\n");
            tr.Commit();
        }
        catch (System.Exception ex)
        {
            ed.WriteMessage($"\nError: {ex.Message}\n");
            tr.Abort();
        }
    }
}
